TRUNCATE TABLE `library_management`.`books`;

INSERT INTO `library_management`.`books` (`id`, `isbn`, `title`, `author`, `available_qty`, `total`, `version`, `image_link`, `description`) 
VALUES 
('1', '3246547', 'A Game of Thrones', 'George R. R. Martin', '1', '1', '1', 'http://books.google.com/books/content?id=btpIkZ6X6egC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'The kingdom of the royal Stark family faces its ultimate challenge in the onset of a generation-long winter, the poisonous plots of the rival Lannisters, the emergence of the Neverborn demons, and the arrival of barbarian hordes'),
('2', '3246548', 'Who Moved My Cheese', 'Spencer Johnson', '1', '1', '1', 'http://books.google.com/books/content?id=toxlBwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'Little friends in a maze find and enjoy some cheese, but when that cheese is gone, only Sniff and Scurry adapt and go searching for more while Hem and Haw wait for more cheese to appear.'),
('3', '3246549', 'The Monk who Sold His Ferrari', 'Robin S. Sharma', '7', '7', '1', 'http://books.google.com/books/content?id=PcKVHXuAo8wC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'This inspiring tale is based on the author\'s own search for life\'s true purpose, providing a step-by-step approach to living with greater courage, balance, abundance and joy.'),
('4', '3246510', 'Harry Potter and the Chamber of Secrets', 'J.K. Rowling', '7', '7', '1', 'http://books.google.com/books/content?id=5iTebBW-w7QC&printsec=frontcover&img=1&zoom=1&source=gbs_api', "Harry Potter's summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors - and then the attacks start."),
('5', '3246567', 'Angels and Demons', 'Dan Brown', '100', '100', '1', 'http://books.google.com/books/content?id=nXrxGCVd9UoC&printsec=frontcover&img=1&zoom=1&source=gbs_api', "A breathless, real-time adventure\' San Francisco Chronicle A famous scientist is found dead, a strange symbol burned brutally into his skin. Many miles away in Rome, the world\'s cardinals assemble to elect a new Pope. Somewhere in the Vatican, a bomb of vast power begins its countdown. Working out the puzzle against the clock, can Robert Langdon stop it detonating?"),
('6', '3246598', 'Sapiens', 'Yuval Noah Harari', '25', '25', '1', 'http://books.google.com/books/content?id=1EiJAwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'What makes us brilliant? What makes us deadly? What makes us Sapiens? Yuval Noah Harari challenges everything we know about being human in the perfect read for these unprecedented times. Earth is 4.5 billion years old. In just a fraction of that time, one species among countless others has conquered it: us.'),
('7', '3246569', 'Marley & Me', 'ohn Grogan', '20', '20', '1', 'http://books.google.com/books/content?id=MKSjqd_1Pr4C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'Follows the life story of an exuberant Labrador retriever who gets into perpetual trouble and experiences a range of inspiring adventures, from shutting down an entire beach to guarding a seventeen-year-old neighbor after a stabbing attack.'),
('8', '3246570', 'Becoming', 'Michelle Obama', '15', '15', '1', 'http://books.google.com/books/content?id=hi17DwAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'In a life filled with meaning and accomplishment, Michelle Obama has emerged as one of the most iconic and compelling women of our era. As First Lady of the United States of America, she helped create the most welcoming and inclusive White House in history');


TRUNCATE TABLE `library_management`.`users`;
INSERT INTO `library_management`.`users` (`id`, `full_name`, `contact_number`, `books_borrowed`, `version`) VALUES ('1', 'Joe', '2342342323', '1', '78');


TRUNCATE TABLE `library_management`.`books_borrowed`;
INSERT INTO `library_management`.`books_borrowed` (`user_id`, `book_id`, `is_borrowed`) VALUES ('1', '1','1');